Fix code that was causing unit test to fail, where unit test was doing a PUT with _deleted=true and expecting a 200 OK response rather than 201 Created.
com.couchbase.lite.RouterTest > testDocs[Nexus 4 - 4.2.2 - API 17 - 768x1280 - 4.2.2] FAILED
	junit.framework.AssertionFailedError: expected:<200> but was:<201>
	at com.couchbase.lite.LiteTestCase.sendBody(LiteTestCase.java:268)