Fix major bug in conflict handling.  testConflict() gets further, but not quite passing yet.
saw testConflict() fail with
        junit.framework.AssertionFailedError: expected:<{dc5e182f-f64e-4d2a-b642-dbe6e1a90ea1 #2-367d8e53-96a9-4475-8457-60b92405e7ff}> but was:<{dc5e182f-f64e-4d2a-b642-dbe6e1a90ea1 #2-84451ede-6a39-47f0-9934-5719bcc814e3}>
        at com.couchbase.lite.ApiTest.testConflict(ApiTest.java:435)